erstarr:
  banned_by: erstarr
  reason: '@erstarr cuuu'
  timestamp: '2026-09-08T02:09:05.083121+00:00'
wabarTM:
  banned_by: erstarr
  reason: '@erstarr  quack'
  timestamp: '2026-09-07T22:31:59.397733+00:00'
