erstarr:
  banned_by: erstarr
  reason: cuu caa cwww cwaa
  timestamp: '2026-09-08T02:24:47.338457+00:00'
wabarTM:
  banned_by: erstarr
  reason: '@erstarr  quack'
  timestamp: '2026-09-07T22:31:59.397733+00:00'
